name: 🧪 Calmoji CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Run tests with coverage
        run: pytest --tb=short --cov=calmoji --cov-branch --cov-report=xml --cov-fail-under=85
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4

